---
title: "Fed-Reported Econonomic Indicators"
output: html_document
---

To install the datasets:

```{r, eval = FALSE}
devtools::install_github('adamacosta/fred')
```

Source: [Federal Reserve Data Download Program](http://www.federalreserve.gov/datadownload/)

```{r, echo = FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
knitr::knit_hooks$set(htmlcap = function(before, options, envir) {
    if (!before) {
        paste0('<p class="caption">', options$htmlcap, '</p>')
    }
})
```

```{r}
library(ggvis)
library(zoo)
library(dplyr)
library(tidyr)
library(lubridate)

data(credit, package = 'fred')
data(assets, package = 'fred')
data(money, package = 'fred')
data(capacity, package = 'fred')
```

## Consumer Credit

```{r, htmlcap = 'Figure 1. Consumer credit balances'}
credit %>%
    na.locf(fromLast = FALSE, na.rm = FALSE) %>%
    gather(type, amount, -period) %>%
    mutate(period = ymd(period), amount = as.numeric(amount)) %>%
    mutate(amount = ifelse(is.na(amount), 0, amount)) %>%
    ggvis(~period, ~amount, stroke = ~type) %>%
    layer_lines() %>%
    add_axis('y', title_offset = 80, title = 'millions USD')
```

# Fed Balance Sheet

```{r, htmlcap = 'Figure 2. Fed balance sheet assets'}
assets %>%
    ggvis(~period, ~assets) %>%
    layer_lines(stroke := 'steelblue') %>%
    add_axis('y', title_offset = 80, title = 'millions USD')
```

## US Money Supply

```{r, htmlcap = 'Figure 3. Money supply'}
money %>%
    gather(measure, usd, -period) %>%
    mutate(usd = ifelse(is.na(usd), 0, usd)) %>%
    ggvis(~period, ~usd, stroke = ~measure) %>%
    layer_lines() %>%
    add_axis('y', title_offset = 80, title = 'millions USD')
```

## Industrial Production and Capacity

```{r, htmlcap = 'Figure 4. Industial capacity utilization'}
capacity %>%
    select(period, utilization) %>%
    ggvis(~period, ~utilization) %>%
    layer_lines(stroke := 'steelblue') %>%
    add_axis('y', title_offset = 50, title = 'percent utilization')
```

```{r, htmlcap = 'Figure 5. Industrial capacity'}
capacity %>%
    select(-utilization) %>%
    gather(measure, index, -period) %>%
    mutate(index = ifelse(is.na(index), 0, index)) %>%
    ggvis(~period, ~index, stroke = ~measure) %>%
    layer_lines() %>%
    add_axis('y', title_offset = 80, title = 'index')
```
